In [3]:
import numpy as np

def crout_lu(A):
    n = len(A)
    A = np.array(A, dtype=float)
    L = np.zeros((n, n))
    U = np.eye(n)  # Diagonal de U é 1

    for k in range(n):
        for i in range(k, n):
            sum_L = sum(L[i, m] * U[m, k] for m in range(k))
            L[i, k] = A[i, k] - sum_L

        for j in range(k + 1, n):
            sum_U = sum(L[k, m] * U[m, j] for m in range(k))
            U[k, j] = (A[k, j] - sum_U) / L[k, k]

    return L, U

def substituicao_direta(L, b):
    n = L.shape[0]
    y = np.zeros(n)
    for i in range(n):
        soma = sum(L[i, j] * y[j] for j in range(i))
        y[i] = (b[i] - soma) / L[i, i]
    return y

def substituicao_reversa(U, y):
    n = U.shape[0]
    x = np.zeros(n)
    for i in reversed(range(n)):
        soma = sum(U[i, j] * x[j] for j in range(i + 1, n))
        x[i] = (y[i] - soma) / U[i, i]
    return x

def norma_infinito(matriz):
    return max(np.sum(np.abs(matriz), axis=1))

def numero_de_condicionamento(A):
    A_inv = np.linalg.inv(A)
    norma_A = norma_infinito(A)
    norma_A_inv = norma_infinito(A_inv)
    return norma_A * norma_A_inv

# Matriz do exemplo
A = np.array([
    [6, 2, 1, 5],
    [3, 5, 1, 2],
    [4, 8, 1, 2],
    [2, 1, 4, 8]], dtype=float)

b = np.array([9, 10, 12,14], dtype=float)

print("\nMatriz A:")
print(A)

print("\nVetor b:")
print(b)

determinante = np.linalg.det(A)
print(f"\nDeterminante da matriz A = {determinante:.5f}")
cond = numero_de_condicionamento(A)
print(f"\nNúmero de condicionamento de A (norma infinito): {cond:.5f}")


if abs(determinante) > 1e-10:
    print("\n A matriz é não singular, logo o sistema Ax = b pode ser resolvido.")


    print("\nPasso 1: Decomposição A = LU (Método de Crout)")
    L, U = crout_lu(A)

    print("\nMatriz L (Triangular Inferior):")
    print(L)

    print("\nMatriz U (Triangular Superior com diagonal = 1):")
    print(U)

    print("\nPasso 2: Resolver Ly = b (substituição direta)")
    y = substituicao_direta(L, b)
    print("Vetor intermediário y =", y)

    print("\nPasso 3: Resolver Ux = y (substituição reversa)")
    x = substituicao_reversa(U, y)
    x_formatado = [f"{val:.5f}" for val in x]
    print("Solução do sistema x =", x_formatado)

else:
    print("A matriz é singular ou quase singular e não pode ser invertida.")
    print("\n Aviso: A matriz A é mal condicionada. Pequenas variações em A ou b podem causar grandes erros na solução.")



Matriz A:
[[6. 2. 1. 5.]
 [3. 5. 1. 2.]
 [4. 8. 1. 2.]
 [2. 1. 4. 8.]]

Vetor b:
[ 9. 10. 12. 14.]

Determinante da matriz A = -33.00000

Número de condicionamento de A (norma infinito): 201.36364

 A matriz é não singular, logo o sistema Ax = b pode ser resolvido.

Passo 1: Decomposição A = LU (Método de Crout)

Matriz L (Triangular Inferior):
[[ 6.          0.          0.          0.        ]
 [ 3.          4.          0.          0.        ]
 [ 4.          6.66666667 -0.5         0.        ]
 [ 2.          0.33333333  3.625       2.75      ]]

Matriz U (Triangular Superior com diagonal = 1):
[[ 1.          0.33333333  0.16666667  0.83333333]
 [ 0.          1.          0.125      -0.125     ]
 [ 0.          0.          1.          1.        ]
 [ 0.          0.          0.          1.        ]]

Passo 2: Resolver Ly = b (substituição direta)
Vetor intermediário y = [ 1.5         1.375       6.33333333 -4.51515152]

Passo 3: Resolver Ux = y (substituição reversa)
Solução do sistema x 

## Decomposição LU – Método de Crout

O método de Crout é uma forma de decomposição LU usada para resolver sistemas lineares, inverter matrizes e calcular determinantes. Assim como o método de Doolittle, ele decompõe uma matriz quadrada A em duas matrizes: uma triangular inferior L e uma triangular superior U, de modo que:

**A = L × U**

No entanto, a principal característica do **método de Crout** é que a matriz **U** possui **1s na diagonal principal**, enquanto a matriz **L** contém os elementos da diagonal e da parte inferior.

Ou seja:
- **L** é uma matriz triangular inferior com valores reais na diagonal;
- **U** é uma matriz triangular superior com **1s na diagonal principal**.

O processo de fatoração consiste em calcular os elementos de L e U a partir dos elementos da matriz A, seguindo um procedimento sistemático que resolve as equações linha por linha e coluna por coluna.

### Aplicações

A decomposição LU pelo método de Crout é usada principalmente para resolver sistemas lineares do tipo Ax = b. O procedimento é dividido em duas etapas:
1. Resolver **Ly = b** por substituição direta;
2. Resolver **Ux = y** por substituição retroativa.

### Vantagens:
- O método de Crout é útil em casos onde é mais conveniente ter a diagonal de U como 1, o que pode simplificar os cálculos em alguns contextos;
- Pode ser implementado de forma eficiente em algoritmos numéricos;
- Funciona bem para matrizes que não exigem pivotamento (ou pode ser adaptado com pivotamento, se necessário).

### Observação:
Para que a decomposição funcione corretamente, a matriz A deve ser quadrada e não-singular. Se houver divisão por zero durante o processo, o método pode falhar, sendo necessário aplicar pivotamento para garantir a estabilidade numérica.

O método de Crout é uma alternativa ao método de Doolittle e faz parte das técnicas fundamentais da álgebra linear computacional.

OBS: nESSE CODIGO DEVE-SE ALTERAR APENAS OS VALORES DAS MATRIZES "A" E "b".


A = np.array([

    [6, 2, 1],
    [3, 5, 1],
    [2, 1, 4]], dtype=float)


b = np.array([9, 10, 12], dtype=float)