In [1]:
import numpy as np

def decomposicao_lu(A):
    """
    Decompõe a matriz A (lista de listas) em L e U sem pivotamento.
    Retorna L e U como listas de listas.
    """
    n = len(A)
    # Inicializa L = identidade e U = cópia de A (float)
    L = [[1.0 if i == j else 0.0 for j in range(n)] for i in range(n)]
    U = [[float(A[i][j]) for j in range(n)] for i in range(n)]

    for k in range(n-1):
        if U[k][k] == 0:
            raise ValueError("Pivô zero encontrado. Pivotamento necessário.")
        for i in range(k+1, n):
            fator = U[i][k] / U[k][k]
            L[i][k] = fator
            # atualiza linha i de U, colunas k..n-1
            for j in range(k, n):
                U[i][j] -= fator * U[k][j]
    return L, U

def substituicao_direta(L, b):
    """
    Resolve L y = b por substituição para frente.
    L deve ter diagonal = 1.
    b pode ser lista de floats.
    """
    n = len(L)
    y = [0.0]*n
    for i in range(n):
        soma = 0.0
        for j in range(i):
            soma += L[i][j] * y[j]
        y[i] = b[i] - soma
    return y

def substituicao_reversa(U, y):
    """
    Resolve U x = y por substituição regressiva.
    """
    n = len(U)
    x = [0.0]*n
    for i in range(n-1, -1, -1):
        soma = 0.0
        for j in range(i+1, n):
            soma += U[i][j] * x[j]
        x[i] = (y[i] - soma) / U[i][i]
    return x

# --- Exemplo de uso ---

# Definição da matriz A como lista de listas
A = np.array([
    [6, 2, 1, 5],
    [3, 5, 1, 2],
    [4, 8, 1, 2],
    [2, 1, 4, 8]], dtype=float)
# Vetor b
b = np.array([9, 10, 12,14], dtype=float)

print("Matriz A:")
for row in A:
    print(row)
print("\nVetor b:", b)

# Cálculo do determinante apenas com numpy
determinante = np.linalg.det(np.array(A, dtype=float))
print(f"\nDeterminante de A = {determinante:.6f}")

if abs(determinante) < 1e-10:
    print("Matriz singular ou quase singular — não é possível resolver o sistema.")
else:
    print("Matriz não singular — vamos resolver Ax = b via LU manual.\n")

    # Decomposição LU
    L, U = decomposicao_lu(A)
    print("Matriz L:")
    for row in L:
        print(row)
    print("\nMatriz U:")
    for row in U:
        print(row)

    # Substituição direta e reversa
    y = substituicao_direta(L, b)
    print(f"\nVetor intermediário y (Ly = b): {y}")

    x = substituicao_reversa(U, y)
    x_fmt = [f"{xi:.5f}" for xi in x]
    print(f"\nSolução x (Ux = y): {x_fmt}")


Matriz A:
[6. 2. 1. 5.]
[3. 5. 1. 2.]
[4. 8. 1. 2.]
[2. 1. 4. 8.]

Vetor b: [ 9. 10. 12. 14.]

Determinante de A = -33.000000
Matriz não singular — vamos resolver Ax = b via LU manual.

Matriz L:
[1.0, 0.0, 0.0, 0.0]
[0.5, 1.0, 0.0, 0.0]
[0.6666666666666666, 1.6666666666666667, 1.0, 0.0]
[0.3333333333333333, 0.08333333333333334, -7.25, 1.0]

Matriz U:
[6.0, 2.0, 1.0, 5.0]
[0.0, 4.0, 0.5, -0.5]
[0.0, 0.0, -0.5, -0.49999999999999967]
[0.0, 0.0, 0.0, 2.750000000000003]

Vetor intermediário y (Ly = b): [np.float64(9.0), np.float64(5.5), np.float64(-3.166666666666668), np.float64(-12.416666666666675)]

Solução x (Ux = y): ['3.63636', '-0.54545', '10.84848', '-4.51515']
